databases:
  - name: render-sample
    databaseName: render-sample
    user: render-sample

services:
  - type: web
    name: render-sample
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render-sample
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
