databases:
  - name: render_sample
    databaseName: render_sample
    user: render_sample

services:
  - type: web
    name: render_sample
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_sample
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
